  
resources:
  - name: maven_repo1
    type: GitRepo
    configuration:
      gitProvider: github_neha
      branches:
        include: ^master$
      path: neha-mishraa/project-examples
pipelines:
  - name: mvn_sample
    steps:
      - name: mvnStep
        type: MvnBuild
        configuration:
          mvnCommand: clean install
          sourceLocation: ./artifactory-maven-plugin-example
          configFileLocation: $res_maven_repo1_resourcePath/artifactory-maven-plugin-example
          configFileName: mvn-art-config
          integrations:
            - name: art_v
          inputResources:
            - name: maven_repo1
        execution:
          onStart:
            - printenv
            - javac -version
            - mvn --version
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete:                                 
            - echo "Cleaning up some stuff"
