  
resources:
  - name: maven_repo1
    type: GitRepo
    configuration:
      gitProvider: github_neha
      path: neha-mishraa/project-examples/artifactory-maven-plugin-example
pipelines:
  - name: mvn_sample
    steps:
      - name: mvnStep
        type: MvnBuild
        configuration:
          mvnCommand: clean install
          sourceLocation: .
          configFileLocation: .
          configFileName: mvn-art-config
          integrations:
            - name: art_v
          inputResources:
            - name: maven_repo1
        execution:
          onStart:
            - javac -version
            - mvn --version
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete:                                 
            - echo "Cleaning up some stuff"
