resources:
  - name: rsc_GR_N_MVN_0022
    type: GitRepo
    configuration:
      gitProvider: github_neha
      branches:
        include: ^master$
      path: neha-mishraa/project-examples
pipelines:
  - name: N_MVN_0022
    configuration:
      nodePool: win_2019
    steps:
      - name: N_MVN_0022_1
        type: MvnBuild
        configuration:
          sourceLocation: artifactory-maven-plugin-example
          configFileLocation: .
          configFileName: mvn-art-config
          integrations:
            - name: art_v
          inputResources:
            - name: rsc_GR_N_MVN_0022
        execution:
          onStart:
            - javac -version
            - mvn --version
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete:                                 
            - echo "Cleaning up some stuff"
