resources:
  - name: rsc_GR_N_MVN_0031
    type: GitRepo
    configuration:
      gitProvider: github_neha
      branches:
        include: ^master$
      path: neha-mishraa/project-examples
pipelines:
  - name: N_MVN_0031
    steps:
      - name: N_MVN_0031_1
        type: MvnBuild
        configuration:
          mvnCommand: clean install
          sourceLocation: artifactory-maven-plugin-example
          resolverReleaseRepo: release-maven-virtual 
          integrations:
            - name: art_v
          inputResources:
            - name: rsc_GR_N_MVN_0031
        execution:
          onStart:
            - javac -version
            - mvn --version
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete:                                 
            - echo "Cleaning up some stuff"
