resources:
  - name: rsc_GR_N_MVN_0002
    type: GitRepo
    configuration:
      gitProvider: github_neha
      branches:
        include: ^master$
      path: neha-mishraa/project-examples
pipelines:
  - name: N_MVN_0002
    steps:
      - name: N_MVN_0002_1
        type: MvnBuild
        configuration:
          mvnCommand: clean install
#           sourceLocation: artifactory-maven-plugin-example
          configFileLocation: ./artifactory-maven-plugin-example
          configFileName: mvn-art-config
          integrations:
            - name: art_v
          inputResources:
            - name: rsc_GR_N_MVN_0002
        execution:
          onStart:
            - printenv
            - echo $res_maven_repo1_resourcePath
            - ls $res_maven_repo1_resourcePath
            - ls $res_maven_repo1_resourcePath/artifactory-maven-plugin-example
            - cat $res_maven_repo1_resourcePath/artifactory-maven-plugin-example/mvn-art-config
            - javac -version
            - mvn --version
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete:                                 
            - echo "Cleaning up some stuff"
