resources:
  - name: rsc_BI_N_PB_0001
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: full-gradle-native
      buildNumber: 1
  - name: rsc_BI_N_PB_0002
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: promotoed-full-gradle-native
      buildNumber: 1
pipelines:
  - name: N_PB_0001
    steps:
      - name: N_PB_0001_1
        type: PromoteBuild
        configuration:
          targetRepository: test-generic-local repo
          #includeDependencies:   <boolean>    # default false
          #status:                <string> 
          #comment:               <string>
          copy: true
          inputResources:
            - name: rsc_BI_N_PB_0001
              trigger: false
          outputResources:
            - name: rsc_BI_N_PB_0002
        execution:
          onStart:
            - echo "Preparing for work..."
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: 
            - echo "Cleaning up some stuff"
