resources:
  - name: S_GoBuild_0022_GitRepo
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: neha-mishraa/nativeSteps
      branches:
        include: {{gitBranch}}

pipelines:
  - name: pipeline_S_GoBuild_0022
    configuration:
      environmentVariables:
        readOnly:
          source_location: "tests/Go/HelloWorld"
    steps:
      - name: S_GoBuild_0022
        type: GoBuild
        configuration:
          integrations:
            - name: art
          inputResources:
            - name: S_GoBuild_0022_GitRepo
          resolverRepo: test-automation-go-virtual
        execution:
          onStart:
            - pushd $(find_resource_variable $inputGitRepoResourceName resourcePath)
            - mv tests/Go/HelloWorld/* .
            - ls
            - popd
