
resources:
  - name: S_GoPublishModule_0038_GitRepo
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: neha-mishraa/nativeSteps
      branches:
        include: {{gitBranch}}

  - name: S_GoPublishModule_0038_BuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: s_artifactory

pipelines:
  - name: pipeline_S_GoPublishModule_0038
    steps:
      - name: S_GoPublishModule_0038_1
        type: GoPublishModule
        configuration:
          environmentVariables:
            auto_publish: "false"
          inputResources:
            - name: S_GoPublishModule_0038_GitRepo
          outputResources:
            - name: S_GoPublishModule_0038_BuildInfo
          version: "v0.38.${run_number}"
          targetRepository: test-automation-go-local
          autoPublishBuildInfo: ${auto_publish}
          sourceLocation: "tests/Go"
      - name: S_GoPublishModule_0038_2
        type: Bash
        configuration:
          inputResources:
            - name: S_GoPublishModule_0038_BuildInfo
          integrations:
            - name: s_artifactory
        execution:
          onExecute:
            - buildInfoName=$(jfrog rt curl -XGET "/api/build/${JFROG_CLI_BUILD_NAME}/${JFROG_CLI_BUILD_NUMBER}" | jq -r .buildInfo.name)
            - if [ "$buildInfoName" != "null" ]; then return 1; fi
