resources:
  - name: S_PublishBuildInfo_0009_output
    type: BuildInfo
    configuration:
      sourceArtifactory: s_artifactory

pipelines:
  - name: pipeline_S_PublishBuildInfo_0009
    steps:
      - name: S_PublishBuildInfo_0009_1
        type: Bash
        configuration:
          integrations:
            - name: s_artifactory
        execution:
          onExecute:
            - echo "${run_id}" > S_PublishBuildInfo_0009.txt
            - $jfrog_cli_path rt upload S_PublishBuildInfo_0009.txt test-automation-generic-local
            - add_run_files /tmp/jfrog/. jfrog
            - add_run_variables buildStepName=S_PublishBuildInfo_0009_1 S_PublishBuildInfo_0009_1_buildName=${JFROG_CLI_BUILD_NAME} S_PublishBuildInfo_0009_1_buildNumber=${JFROG_CLI_BUILD_NUMBER}
      - name: S_PublishBuildInfo_0009_2
        type: PublishBuildInfo
        configuration:
          outputResources:
            - name: S_PublishBuildInfo_0009_output
          inputSteps:
            - name: S_PublishBuildInfo_0009_1
      - name: S_PublishBuildInfo_0009_3
        type: Bash
        configuration:
          integrations:
            - name: s_artifactory
          inputResources:
            - name: S_PublishBuildInfo_0009_output
        execution:
          onExecute:
            - if [ "$res_S_PublishBuildInfo_0009_output_buildName" != "${JFROG_CLI_BUILD_NAME}" ]; then return 1; fi
            - if [ "$res_S_PublishBuildInfo_0009_output_buildNumber" != "${JFROG_CLI_BUILD_NUMBER}" ]; then return 1; fi
            - jfrog rt curl -XDELETE /api/build/${JFROG_CLI_BUILD_NAME}?buildNumbers=${JFROG_CLI_BUILD_NUMBER}&artifacts=1
